
services:

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mobius-db
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "bindsoft"
      MYSQL_DATABASE: "mobiusdb"
    ports:
      - "3307:3306"
    volumes:
      - ./Mobius/mobius/mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql
    healthcheck:  # 서비스 헬스체크
      test: ["CMD", "mysqladmin", "ping"]
      interval: 20s
      timeout: 20s
      retries: 5
    networks:
      - mobius-net  # 사용자 정의 네트워크에 연결

  node:
    image: node:14.15.2
    container_name: mobius-server
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
    volumes:
      - ./Mobius:/home/node/app
    expose:
      - "8081"  # 다른 컨테이너에서 접근 가능한 포트 (외부에서는 접근 불가)
    ports:
      - "7579:7579"  # 외부 접근 포트
    command: sh -c "npm install && node --expose_gc mobius"
    depends_on:
      db:
        condition: service_healthy  # DB 서비스가 헬시 상태일 때만 실행
    networks:
      - mobius-net  # 사용자 정의 네트워크에 연결

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config  # 설정 파일 마운트 (읽기 전용)
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mobius-net  # 사용자 정의 네트워크에 연결

  device-simulator:
    build: ./device-simulator
    container_name: device-simulator
    working_dir: /usr/src/app
    environment:
      - MOBIUS_HOST=node
      - MOBIUS_PORT=7579
    depends_on:
      - node
    ports:
      - "8369:8369"
    networks:
      - mobius-net  # 사용자 정의 네트워크에 연결

networks:
  mobius-net:  # 컨테이너 간 통신을 위한 사용자 정의 브리지 네트워크
    driver: bridge


